config/routes.rb
Rails.application.routes.draw do

  resources :event_triggers do
    get :remove, on: :member
  end

  resources :mail_messages do
    get :remove, on: :member
  end

  root to: 'dashboard#index'
  get 'dashboard' => 'dashboard#index'

  devise_for :users
  namespace :api, constraints: { format: 'json' } do
    post 'incoming_events' => 'incoming_events#create'
  end

end

app/models/mail_message.rb
# MailMessage handles with a email messages
# that can be delivered via events
class MailMessage < ActiveRecord::Base
  paginates_per 20
  max_paginates_per 100
  validates :label, uniqueness: true, format: { with: /\A[a-z\_0-9]+\z/ }
  validates :label, :subject, :body, presence: true

  attr_accessor :parsed_subject, :parsed_body

  def to_s
    label
  end

  # handles with template parse for message
  # attributes should be in format:
  # attrs = {
  #   user: {
  #     'var1' => 'lorem'
  #   }
  # }
  def parse(attrs)
    parse_subject(attrs)
    parse_body(attrs)
  end

  # parse subject_template with given attributes
  # rendered template are stored into parsed_subject
  def parse_subject(attrs = {})
    self.parsed_subject = subject_template.render(
      attrs.deep_stringify_keys, strict_variables: true)
  end

  # parse body_template with given attributes
  # rendered template are stored into parsed_body
  def parse_body(attrs = {})
    self.parsed_body = body_template.render(
      attrs.deep_stringify_keys, strict_variables: true)
  end

  # subject template over template parser
  def subject_template(parser = template_parser)
    @st ||= parser.parse(subject)
  end

  # body template over template parser
  def body_template(parser = template_parser)
    @bt ||= parser.parse(body)
  end


  def template_parser
    Liquid::Template
  end

end

app/controllers/mail_messages_controller.rb
class MailMessagesController < ApplicationController
  respond_to :html

  def index
    @mail_messages = MailMessage.order(created_at: :desc).page(params[:page])
    respond_with @mail_messages
  end

  def show
    @mail_message = MailMessage.find(params[:id])
    respond_with @mail_message
  end

  def new
    @mail_message = MailMessage.new
    respond_with @mail_message
  end

  def edit
    @mail_message = MailMessage.find(params[:id])
    respond_with @mail_message
  end

  def create
    @mail_message = MailMessage.new(mail_message_params)
    flash[:notice] = 'email template created' if @mail_message.save
    respond_with @mail_message
  end

  def update
    @mail_message = MailMessage.find params[:id]
    @mail_message.update_attributes(mail_message_params)

    if @mail_message.valid?
      flash[:notice] = 'email template updated'
      redirect_to @mail_message
    else
      render :edit
    end
  end

  def remove
  end

  def destroy
  end

  def mail_message_params
    params.require(:mail_message).permit(:label, :subject, :body)
  end
end

app/views/mail_messages/_form.html.slim
= simple_form_for @mail_message do |f|
  = f.error_notification

  = f.input :label, as: :string
  = f.input :subject, input_html: { rows: 2 }
  = f.input :body

  = f.button :submit

app/views/mail_messages/edit.html.slim
.mui-container-fluid
  h1= "Edit messa #{@mail_message.label}"
  = render 'form'

app/views/mail_messages/index.html.slim
.ui.main.text.container
  h1.ui.header Email templates

  .ui.pointing.menu
    = link_to 'All', mail_messages_path, class: 'active item'
    = link_to 'New template', new_mail_message_path, class: 'item'
    .right.menu
      .item
        .ui.transparent.icon.input
          input[type="text" placeholder="Search..."]
          i[class="search link icon"]

  table.ui.celled.table
    thead
      tr
        th label
    tbody
      - @mail_messages.each do |resource|
        tr
          td
            span= link_to resource.label, resource
    tfoot
      tr
        th
          = paginate @mail_messages

app/views/mail_messages/new.html.slim
.ui.main.text.container
  h1.ui.header New email message template

  .ui.segment
    = render 'form'

app/views/mail_messages/remove.html.slim
h1 MailMessages#remove
p Find me in app/views/mail_messages/remove.html.slim

app/views/mail_messages/show.html.slim
.mui-container-fluid
  h1= @mail_message.label
  br/
  strong subject template
  br/
  = @mail_message.subject
  br/
  br/
  strong body template
  br/
  = simple_format(@mail_message.body)

app/views/mail_messages/update.html.slim
h1 MailMessages#update
p Find me in app/views/mail_messages/update.html.slim