config/routes.rb
Rails.application.routes.draw do

  resources :event_triggers do
    get :remove, on: :member
  end

  resources :mail_messages do
    get :remove, on: :member
  end

  root to: 'dashboard#index'
  get 'dashboard' => 'dashboard#index'

  devise_for :users
  namespace :api, constraints: { format: 'json' } do
    post 'incoming_events' => 'incoming_events#create'
  end

end

app/models/event_trigger.rb
# EventTrigger works like a dispatcher for with incoming events
class EventTrigger < ActiveRecord::Base
  has_many :mail_actions, class_name: 'EventTriggerMailAction'

  validates :trigger_name, :description, presence: true
  validates :trigger_name, uniqueness: true, format: { with: /\A[a-z\_0-9]+\z/ }

  accepts_nested_attributes_for :mail_actions, allow_destroy: true

  def to_s
    trigger_name
  end

  def self.trigger_titles
    all.pluck(:trigger_name).map do |x|
      { title: x }
    end
  end
end

app/controllers/event_triggers_controller.rb
class EventTriggersController < ApplicationController
  respond_to :html
  has_scope :search

  def index
    @event_triggers = apply_scopes(EventTriggerCatalog).all.page(params[:page])
    respond_with @event_triggers
  end

  def show
    @event_trigger = EventTrigger.find params[:id]
    @event_trigger_catalog = EventTriggerCatalog.find_by_event_trigger_id params[:id]

    @event_trigger.mail_actions.build unless @event_trigger.mail_actions.present?
    respond_with @event_trigger
  end

  def new
    @event_trigger = EventTrigger.new
  end

  def edit
    @event_trigger = EventTrigger.find params[:id]
    respond_with @event_trigger
  end

  def create
    @event_trigger = EventTrigger.new(event_trigger_params)
    flash[:notice] = 'event trigger created' if @event_trigger.save
    respond_with @event_trigger
  end

  def update
    @event_trigger = EventTrigger.find params[:id]
    @event_trigger.update_attributes(event_trigger_params)

    if @event_trigger.valid?
      flash[:notice] = 'event trigger updated'
      redirect_to @event_trigger
    else
      if event_trigger_params[:mail_actions_attributes].present?
        render :show
      else
        render :edit
      end
    end
  end

  def remove
  end

  def destroy
  end

  def event_trigger_params
    params.require(:event_trigger).permit(:trigger_name, :description, mail_actions_attributes: %i( mail_message_id event_trigger_id ))
  end
end

app/views/event_triggers/_form.html.slim
= simple_form_for @event_trigger do |f|
  = f.error_notification

  = f.input :trigger_name
  = f.input :description

  = f.button :submit

app/views/event_triggers/edit.html.slim
.mui-container-fluid
  h1 Edit event trigger
  = render 'form'

app/views/event_triggers/index.html.slim
css:
  sgv {
    display: block;
    width: 100%;
  }


.ui.inverted.vertical.center.aligned.segment.herop-header
  .ui.text.main.container[style="margin-bottom: 1em; margin-top: 4em;"]
    h1.ui.header.inverted
      /i.puzzle.icon.circular
      .content
        | Event triggers
        .sub.header Create and analyze triggered actions for incomming events


.ui.main.text.container.with-3d-shadow.with-transitions[style="margin-top: 2em;"]
  .ui.secondary.menu[style="margin-bottom: 2em;"]
    = link_to new_event_trigger_path, class: 'ui compact labeled icon button olive' do
      i.icon.plus
      | new trigger
    .right.menu
      .item
        form#event_trigger_search.ui.icon.input.search[data-evnames=EventTrigger.trigger_titles.to_json action=event_triggers_path(params) method='get']
          input[type="text" class="prompt" placeholder="Search..." name="search" value=params[:search]]
          i[class="search link icon"]

  - @event_triggers.each do |resource|
    .ui.segments[style='margin: 2em 0']
      .ui.segment
        .ui.grid
          .ten.wide.column
            .ui.ribbon.label.large
              = resource['trigger_name']
          .six.wide.column
            .ui.buttons.right.floated.icon
              = link_to event_trigger_path(resource['event_trigger_id']), class: 'ui button icon' do
                i.pie.chart.icon
              = link_to event_trigger_path(resource['event_trigger_id']), class: 'ui button icon' do
                i.heartbeat.icon
              = link_to edit_event_trigger_path(resource['event_trigger_id']), class: 'ui button icon' do
                i.edit.icon
        - if resource.last_activity.present?
          svg.chart-data[id="chart-#{resource['event_trigger_id']}"data-activity=resource.last_activity.data.to_json]


  = paginate @event_triggers

app/views/event_triggers/new.html.slim
.mui-container-fluid
  h1 New event trigger
  = render 'form'

app/views/event_triggers/remove.html.slim
h1 EventTriggers#remove
p Find me in app/views/event_triggers/remove.html.slim

app/views/event_triggers/show.html.slim
.mui-container-fluid
  h1= @event_trigger.trigger_name
  br/
  strong trigger name
  br/
  = @event_trigger.trigger_name
  br/
  br/
  strong description
  br/
  = simple_format(@event_trigger.description)

  hr/
  h2 Mail message to deliver when execute trigger
  = simple_form_for @event_trigger do |f|
    = f.simple_fields_for :mail_actions do |ma|
      = ma.association :mail_message
      = f.button :submit